<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29260" started-at="2019-01-26T18:47:28Z" finished-at="2019-01-26T18:47:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29260" started-at="2019-01-26T18:47:28Z" finished-at="2019-01-26T18:47:57Z">
      <class name="org.testing.TestScripts.TC3">
        <test-method status="PASS" signature="browserInitiate()[pri:0, instance:org.testing.TestScripts.TC3@1500955a]" name="browserInitiate" is-config="true" duration-ms="13898" started-at="2019-01-26T18:47:28Z" finished-at="2019-01-26T18:47:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitiate -->
        <test-method status="FAIL" signature="thirdTestCase()[pri:0, instance:org.testing.TestScripts.TC3@1500955a]" name="thirdTestCase" duration-ms="15324" started-at="2019-01-26T18:47:42Z" finished-at="2019-01-26T18:47:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [shubhamcer@gmail.com] but found [shubhamcert@gmail.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [shubhamcer@gmail.com] but found [shubhamcert@gmail.com]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.testing.TestScripts.TC3.thirdTestCase(TC3.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTestCase -->
      </class> <!-- org.testing.TestScripts.TC3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
